### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by dcryan** [Matttaylor8910/generals-enhancement-suite#21]
Gotta say, I love the minimalistic approach of this app, but I can't get it to install on my machine. 🤪

## Behavior
- none

## Expected
![](https://media.giphy.com/media/Um3ljJl8jrnHy/giphy.gif)

**Comment by Matttaylor8910** [comment]
Have you tried turning your computer off and on again? As an aside, we're meeting at Bar G at noon tomorrow if you're feeling like a beer 😉
